"""init

Revision ID: b05cfc9485cb
Revises: 9359f938d521
Create Date: 2019-02-25 18:08:27.141414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05cfc9485cb'
down_revision = '9359f938d521'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt', sa.DateTime(), nullable=True),
    sa.Column('title', sa.UnicodeText(), nullable=True),
    sa.Column('name', sa.UnicodeText(), nullable=True),
    sa.Column('slug', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_results'))
    )
    op.drop_table('allresults')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allresults',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dt', sa.DATETIME(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('slug', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_allresults')
    )
    op.drop_table('results')
    # ### end Alembic commands ###
